"""
Domain models for DUMb_AI.

These classes describe the core objects in the project. They intentionally
contain no database, API, TUI, or Ollama-specific code.
"""

from __future__ import annotations

from dataclasses import dataclass, field
from datetime import datetime
from enum import Enum
from uuid import UUID


class DocumentStatus(str, Enum):
    """Lifecycle state of an uploaded document during ingestion."""

    UPLOADED = "uploaded"
    PARSED = "parsed"
    CHUNKED = "chunked"
    EMBEDDED = "embedded"
    STORED = "stored"
    READY = "ready"
    FAILED = "failed"


class IngestionStatus(str, Enum):
    """Status of an ingestion pipeline event/job."""

    STARTED = "started"
    PARSED = "parsed"
    CHUNKED = "chunked"
    EMBEDDED = "embedded"
    STORED = "stored"
    COMPLETED = "completed"
    FAILED = "failed"


@dataclass
class Document:
    """
    Parsed document uploaded by a user.

    A parser creates this object from a file. Later ingestion steps split its
    content into chunks, generate embeddings, and store the result.
    """

    id: UUID
    user_id: UUID
    content: str
    filename: str
    uploaded_at: datetime
    content_type: str = "text/plain"
    status: DocumentStatus = DocumentStatus.PARSED
    error_message: str | None = None
    schema_version: int = 1

    def mark_status(self, status: DocumentStatus) -> None:
        self.status = status
        if status is not DocumentStatus.FAILED:
            self.error_message = None

    def mark_failed(self, message: str) -> None:
        self.status = DocumentStatus.FAILED
        self.error_message = message


@dataclass
class Chunk:
    """
    Small text piece produced from a Document.

    The embedding is filled later by EmbeddingObserver. similarity is usually
    filled only for search results returned by the vector store.

    Identity:
        Chunks are identified by the natural composite key (doc_id, position),
        matching the unique index in infra/mongo/init_db.js. No separate
        surrogate UUID is carried on the dataclass — MongoDB's _id is the
        on-disk surrogate when one is needed programmatically.
    """

    text: str
    doc_id: UUID
    user_id: UUID
    position: int
    embedding: list[float] = field(default_factory=list)
    similarity: float | None = None
    metadata: dict[str, object] = field(default_factory=dict)
    created_at: datetime | None = None
    schema_version: int = 1

    @property
    def has_embedding(self) -> bool:
        return bool(self.embedding)


@dataclass
class IngestionEvent:
    """
    Message passed from IngestionService to ingestion observers.

    Observers may mutate chunks in-place. For example, ChunkingObserver fills
    chunks, EmbeddingObserver fills chunk embeddings, and StorageObserver stores
    the final chunks.
    """

    document: Document
    chunks: list[Chunk] = field(default_factory=list)
    status: IngestionStatus = IngestionStatus.STARTED
    error_message: str | None = None

    def fail(self, message: str) -> None:
        self.status = IngestionStatus.FAILED
        self.error_message = message
        self.document.mark_failed(message)


@dataclass
class QueryResult:
    """Answer generated by the RAG query pipeline."""

    answer: str
    sources: list[Chunk] = field(default_factory=list)

    def top_sources(self, n: int) -> list[Chunk]:
        return self.sources[:n]